# Generated by Django 5.1.3 on 2024-11-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Major',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('match_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Match',
            },
        ),
        migrations.CreateModel(
            name='Rally',
            fields=[
                ('rally_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Rally',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Sport',
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('game_result_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('rank', models.BigIntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.match')),
            ],
            options={
                'db_table': 'GameResult',
            },
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('player_score_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('student_id', models.BigIntegerField()),
                ('gameResult_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.gameresult')),
            ],
            options={
                'db_table': 'PlayerScore',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='rally_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.rally'),
        ),
        migrations.AddField(
            model_name='match',
            name='sport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.sport'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_num', models.BigIntegerField(blank=True, null=True)),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.major')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rally_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.rally')),
                ('sport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.sport')),
            ],
            options={
                'db_table': 'Team',
            },
        ),
        migrations.AddField(
            model_name='gameresult',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.team'),
        ),
        migrations.CreateModel(
            name='TeamStudentMapping',
            fields=[
                ('team_student_mapping_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.team')),
            ],
            options={
                'db_table': 'Team-Student_Mapping',
            },
        ),
    ]
