# Generated by Django 5.1.3 on 2024-11-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rally',
            old_name='EndDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='rally',
            old_name='StartDate',
            new_name='start_date',
        ),
    ]
