# Generated by Django 5.1.3 on 2024-11-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='competition',
            table='Competition',
        ),
    ]
