# Generated by Django 5.1.3 on 2024-11-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_competition_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamstudentmapping',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='teamstudentmapping',
            old_name='team_id',
            new_name='team',
        ),
    ]
