# Generated by Django 5.1.3 on 2024-11-11 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_gameresult_game_result_id_alter_major_major_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='group',
        ),
    ]
