# Generated by Django 5.1.3 on 2024-11-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_student_id_teamstudentmapping_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='Competition_id',
            new_name='competition_id',
        ),
    ]
